server:
  port: 8761
  
spring:
  cloud:
    config:
      fail-fast: true
  
eureka:
  instance:
    hostname: localhost
  ## eureka by default will register itself as a client. So, we need to set it to false.
  client:
    # REMOVE IN PROD
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com.netflix.eureka: INFO
    org.springframework.cloud: DEBUG
    ROOT: INFO
