server:
  port: 8090

spring:
  cloud:
    config:
      fail-fast: true
  boot:
    admin:
      client:
        url: http://localhost:8080
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: web # rabbit in prod

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10 # Remove in prod

# To enable all actuator endpoints for admin-server
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  # Sets ${LOG_PATH} in logback-spring.xml
  path: logs
  level:
    org.springframework.cloud: INFO
    org.springframework.cloud.config.server: INFO
    org.springframework.web: INFO
    ROOT: INFO
