server:
  port: 8090
  
spring:
  profiles.active: dev
  cloud:
    config:
      fail-fast: true
  boot:
    admin:
      client:
        url: http://localhost:8080
      
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10 # Remove in prod

# To enable all actuator endpoints for admin-server
management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: dev
logging:
  file: logs/qr-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.netflix.discovery: OFF
    org.springframework.cloud: DEBUG
    org.springframework.cloud.config.server: INFO
    org.springframework.web: INFO
    ROOT: INFO
---
spring:
  profiles: prod
logging:
  file: logs/qr-service.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    com.netflix.discovery: OFF
    org.springframework.cloud: INFO
    org.springframework.cloud.config.server: INFO
    org.springframework.web: INFO
    ROOT: INFO
